# AppWidgetProvider and the manifest receivers are instantiated reflectively by the
# framework from their manifest entries; keep them (the manifest keep-rules generated by
# AGP already cover this, but being explicit survives manifest refactors).
-keep class dev.wherop.batterywidget.BatteryWidgetProvider { *; }
-keep class dev.wherop.batterywidget.PowerEventReceiver { *; }
